apiVersion: v1
kind: Service
metadata:
  name: twodomains-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: twodomains-frontend
